[phases.setup]
nixPkgs = ["php"]

[phases.install]
cmds = ["echo 'No additional installation needed'"]

[phases.build]
cmds = ["echo 'Build complete - PHP application ready'"]

[start]
cmd = "php -S 0.0.0.0:$PORT"
