[phases.setup]
nixPkgs = ["php"]

[phases.install]
cmds = ["echo 'No additional installation needed'"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd public && php -S 0.0.0.0:$PORT"
