[phases.setup]
nixPkgs = ["php", "phpPackages.composer"]

[phases.install]
cmds = ["echo 'Installing PHP dependencies...'"]

[phases.build]
cmds = ["echo 'Build complete - PHP application ready'"]

[start]
cmd = "cd public && php -S 0.0.0.0:$PORT"
